rule_files:
  - "alert.rules.yml"
  
groups:
  - name: example
    rules:
      - alert: HighCpuUsage
        expr: rate(node_cpu_seconds_total[2m]) > 0.85
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected"
