name: CI/CD Monitoring Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Push Docker Images to ECR
      run: |
        docker build -t <ECR_URL>/prometheus-grafana .
        docker push <ECR_URL>/prometheus-grafana
